
sharding:
  jdbc:
    datasource:
      names: ds-master-0,ds-master-1,ds-master-0-slave-0,ds-master-0-slave-1,ds-master-1-slave-0,ds-master-1-slave-1
      ds-master-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/demo_ds_master_0
        username: root
        password: 123456
        minimum-idle: 10
        maximum-pool-size: 30
        auto-commit: true
        idle-timeout: 60000
        max-lifetime: 1800000
        connection-test-query: SELECT 1
        connection-timeout: 60000
      ds-master-0-slave-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/demo_ds_master_0
        username: root
        password: 123456
        minimum-idle: 10
        maximum-pool-size: 30
        auto-commit: true
        idle-timeout: 60000
        max-lifetime: 1800000
        connection-test-query: SELECT 1
        connection-timeout: 60000      
      ds-master-0-slave-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/demo_ds_master_0
        username: root
        password: 123456
        minimum-idle: 10
        maximum-pool-size: 30
        auto-commit: true
        idle-timeout: 60000
        max-lifetime: 1800000
        connection-test-query: SELECT 1
        connection-timeout: 60000    
      ds-master-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/demo_ds_master_1
        username: root
        password: 123456
        minimum-idle: 10
        maximum-pool-size: 30
        auto-commit: true
        idle-timeout: 60000
        max-lifetime: 1800000
        connection-test-query: SELECT 1
        connection-timeout: 60000
      ds-master-1-slave-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/demo_ds_master_1
        username: root
        password: 123456
        minimum-idle: 10
        maximum-pool-size: 30
        auto-commit: true
        idle-timeout: 60000
        max-lifetime: 1800000
        connection-test-query: SELECT 1
        connection-timeout: 60000     
      ds-master-1-slave-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/demo_ds_master_1
        username: root
        password: 123456
        minimum-idle: 10
        maximum-pool-size: 30
        auto-commit: true
        idle-timeout: 60000
        max-lifetime: 1800000
        connection-test-query: SELECT 1
        connection-timeout: 60000    
    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: app_id
            algorithm-expression: ds_$->{app_id}
        binding-tables:
          - t_order,t_order_item
        tables:
          t_order: 
            actual-data-nodes: ds_$->{0..1}.t_order_$->{0..1}
            tables-strategy: 
              inline:
                sharding-column: order_id
                algorithm-expression: t_order_$->{order_id % 2}
            key-generator-column-name: order_id  
          t_order_item:
            actual-data-nodes: ds_$->{0..1}.t_order_item_$->{0..1}
            tables-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: t_order_item_$->{order_id % 2}  
            key-generator-column-name: order_item_id  
        master-slave-rules:
          ds_0:
            master-data-source-name: ds-master-0
            slave-data-source-names: [ds-master-0-slave-0,ds-master-0-slave-1]
            load-balance-algorithm-type: ROUND_ROBIN
          ds_1:
            master-data-source-name: ds-master-1
            slave-data-source-names: [ds-master-1-slave-0,ds-master-1-slave-1]
            load-balance-algorithm-type: ROUND_ROBIN
        props:
          sql.show: false    
#          executor.size: 1       
      orchestration:
        name: demo_yaml_ds_sharding_ms
        type: sharding
        overwrite: true
        zookeeper:
          namespace: orchestration-yaml-demo
          server-lists: localhost:2181
server:
  port: 7211     